export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_SIGNUP_USER_FAILURE = 'AUTH_SIGNUP_USER_FAILURE';
export const AUTH_SIGNUP_USER_REQUEST = 'AUTH_SIGNUP_USER_REQUEST';
export const AUTH_SIGNUP_USER_SUCCESS = 'AUTH_SIGNUP_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
