# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('o', 'One sided'), ('t', 'Two sided (learn front to back and back to front)'), ('d', 'Derivation')], default='o', help_text='Type of card', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('side', models.CharField(choices=[('fr', 'Front'), ('bk', 'Back')], default='fr', help_text='Role for the face of the card', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='back',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_for_back', to='card.Face'),
        ),
        migrations.AddField(
            model_name='card',
            name='front',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_for_front', to='card.Face'),
        ),
    ]
