# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20161224_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Face',
        ),
        migrations.AddField(
            model_name='derivationstep',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivation_steps', to='card.Card'),
        ),
    ]
