# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 05:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20161226_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='easiness',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='card',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(0, 300)),
        ),
        migrations.AddField(
            model_name='card',
            name='repetition_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='scheduled_for',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 27, 5, 18, 28, 307602, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
