# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 20:22
from __future__ import unicode_literals

from django.contrib.auth.models import User
from ..models import Deck, Card

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_owner_forward(apps, schema_editor):
    """
    Not very safe unless the database is very new, so since I'm the only user,
    should be fine
    """
    try:
        initial_admin = User.objects.get(email='chstansbury')
    except User.DoesNotExist:
        initial_admin = User.objects.first()

    Card.objects.update(owner=initial_admin)
    Deck.objects.update(owner=initial_admin)


def set_owner_backward(apps, schema_editor):
    # Don't bother to do anything since the field is about to be erased
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0004_auto_20161227_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # Go and add the user
        migrations.RunPython(set_owner_forward, set_owner_backward),
    ]
