from datetime import timedelta

CORRECT_RESPONSE_WITH_EASE = 5
CORRECT_RESPONSE_WITH_HESITATION = 4
CORRECT_RESPONSE_WITH_DIFFICULTY = 3
INCORRECT_RESPONSE_WITH_CORRECT_REMEMBERED = 2
INCORRECT_RESPONSE = 1
FUMBLE = 0

MAX_QUALITY = 5
MIN_QUALITY = 0

MAX_EASINESS = 2.5
MIN_EASINESS = 1.3

SRS_EPSILON = timedelta(minutes=5)
